create table public.likes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  upload_id bigint references public.uploads(id) on delete cascade not null,
  guest_hash text not null,
  unique(upload_id, guest_hash)
);

-- Enable RLS
alter table public.likes enable row level security;

-- Allow anonymous access
create policy "Allow public read access"
  on public.likes for select
  using ( true );

create policy "Allow public insert access"
  on public.likes for insert
  with check ( true );

create policy "Allow public delete access"
  on public.likes for delete
  using ( true );
