create table public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  upload_id bigint references public.uploads(id) on delete cascade not null,
  content text not null,
  guest_name text,
  is_couple_reply boolean default false
);

-- Enable RLS
alter table public.comments enable row level security;

-- Allow anonymous access (since guests are anon)
create policy "Allow public read access"
  on public.comments for select
  using ( true );

create policy "Allow public insert access"
  on public.comments for insert
  with check ( true );
